[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [{name = "Alexey Nesterenko", email = "comcon1@pm.me"}]
description = "Toy genome handler"
version = "0.0.1"
keywords = [
    "Test project",
]
license = "GPL-3.0-or-later"
name = "toy_genome_handler"
readme = "README.md"

[project.urls]
repository = "https://github.com/comcon1/toy_genome_handler"

[tool.pytest.ini_options]
testpaths = "tests"
markers = [
    "unit: run unit tests",
    "integration: run integration tests",
]

[tool.ruff]
target-version = "py310"
# Set the maximum line length to 120
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
extend-select = ["E501"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
